### ISSUE TITLE
More native support for installing remote helm charts

### ISSUE THREAD

**Issue by rpocase** [tilt-dev/tilt#2663]
Installing remote helm charts feels a bit counter intuitive today. The options seem to be:

```python
#fetch, then use helm local 
local_resource('fetch_resource_name', 'helm fetch yourupstream --fetch')
k8s_yaml(helm('yourupstream'))

#raw helm upgrade
local_resource('install_resource_name', 'helm upgrade --install yourupstream_release yourupstream')
```
It would be nice to have first class support for installation. This coincides slightly with #1699 , but is a distinct subset of features that would warrant support in that system.

**Comment by maiamcc** [comment]
Good point, we'll take a look.

Note that it would be much easier to implement "Tilt fetches the remote chart, and runs whatever it fetched" and much harder to implement "Tilt fetches the remote chart, and if the remote chart changes, Tilt pulls down the new one" -- would the former suffice for your use case? Any thoughts about these two different behaviors?

**Comment by rpocase** [comment]
I expect the first option is sufficient for most users. I wouldn't expect the latter unless it was a specific integration with `helmfile`. 

Based on your wording, I assume the thought process was a thin wrapper around the first example in the issue. With helm 3, CRDs are no longer templated and are not installed when using `helm template`, making this approach less viable when needing to consume upstream CRDs. I expect supporting this strictly through `helm install` or `helm upgrade --install` has other downsides, though (e.g., would need helm specific resource cleanup). This feels like a separate issue entirely, but at least wanted to note it here.

**Comment by bitsofinfo** [comment]
i'm new to tilt and evaluating it. My existing process is to use helm install/upgrade to deploy the pushed image. I guess I could have helm template go against that chart w/ same values , then resulting YAML goes to k8s_yaml but thats a little awkward imho. i guess it would work, but thats a pretty strict convention being enforced by tilt i guess

**Comment by ahoward1024** [comment]
For anyone who stumbles across this, there is now a tilt extension for installing remote charts:
https://github.com/tilt-dev/tilt-extensions/tree/master/helm_remote

**Comment by nicks** [comment]
A lot of work has gone into [the helm_remote extension](https://github.com/tilt-dev/tilt-extensions/tree/master/helm_remote) to make it both fast and easy to use. So I'm going to close this issue, since I think it fixes most of the problem here.

There's a subtle tangential issue here that @rpocase noted above - Tilt's `helm` and `helm_remote` functions use `helm template` to interoperate with Helm. There are some features of `helm install` that aren't captured quite right in `helm template`. But it's probably better to raise those as separate issues (like this one: https://github.com/tilt-dev/tilt/issues/3658)
