### ISSUE TITLE
Multiple docker_compose calls should be allowed

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#2818]
```
docker_compose([
  'docker-compose.yml',
  'docker-compose2.yml'
])
```
ought to be equivalent to
```
docker_compose('docker-compose.yml')
docker_compose('docker-compose2.yml')
```
but today, the latter fails with: 
> already have a docker-compose resource declared ([.../docker-compose.yml]), cannot declare another

I think this error is a holdover from the days when we only allowed a single docker compose config. now that we allow multiple, this error should go away. (However, this is low priority, as there's an alternate syntax that lets you do the same thing.)

thanks to @tmc for the report

**Comment by maiamcc** [comment]
for conditional includes:
```
yamls = ['a.yaml']
if condition:
  yamls.append('b.yaml')
docker_compose(yamls)
```

**Comment by nicks** [comment]
Some small notes when I investigated this: 

These two syntaxes are equivalent if the docker-compose files are in the same Tiltfile and orthogonal. 

But in practice, this can be a bit trickier because:
- two calls could be in different tiltfiles
- docker-compose files can override each other

Right now, docker_compose() parses the files immediately (at execution time), whereas if there were multiple calls we might have to parse the files at the end of tiltfile execution (at assembly time), so that the overrides work ok.

**Comment by nicks** [comment]
I'm going to re-categorize this as an enhancement request, because it seems more like new functionality

**Comment by nicks** [comment]
fixed by https://github.com/tilt-dev/tilt/pull/3377
