### ISSUE TITLE
Add escape hatch support for passing arbitrary flags in to "docker build" calls as docker_build arguments

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#2840]
There have been a few cases where it would have been nice if we had a way to pass arbitrary flags in to `docker build` from a `docker_build` call in our Tiltfile:
* https://github.com/windmilleng/tilt/issues/2736
* https://github.com/windmilleng/tilt/issues/2839

Could an argument be added to `docker_build` that lets arbitrary flags be passed into the `docker build` execution?

**Comment by nicks** [comment]
For what it's worth, I usually think of `custom_build` as this escape-hatch. Would that work for you?

In the medium-term, we're working on a more full-featured extension system. I could imagine a `docker_build_cli` extension that invokes docker build as a separate process, and allowed you to pass arbitrary flags.

docker_build currently supports some features that need to interface directly with the docker API. Passing arbitrary flags isn't trivial, because you usually need custom code to map from the CLI flags to the API. Maybe a short term fix for this would be to have an api like

```
docker_build(api_options={"Tags": ["foo"]})
```

that modified the API object (https://godoc.org/github.com/docker/docker/api/types#ImageBuildOptions)

**Comment by andymartin-sch** [comment]
> For what it's worth, I usually think of custom_build as this escape-hatch. Would that work for you?

yeah that does work as a workaround

the medium-term proposal sounds good too, although it might make sense to wait until you hear more people asking for this. we are not blocked on https://github.com/windmilleng/tilt/issues/2839 and can continue manually tagging images for now.

**Comment by lizzthabet** [comment]
i'm going to close this issue for now, since `custom_build` is a good solution and the use-cases outlined in the issue have been addressed!
