### ISSUE TITLE
Provide a way to categorize uncategorized k8s objects

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#2989]
When Tilt loads K8s YAML, each workload it finds becomes a resource, but other objects like ConfigMaps and Secrets just end up under "uncategorized".

This can be annoying for a few reasons, which might be addressed by different solutions:
1. It feels literally unorganized
2. They can end up consuming a whole lot of real estate relative to the actual resources, e.g.:
![image](https://user-images.githubusercontent.com/7453991/75051062-38ede400-549b-11ea-8639-2ed88fda244f.png)
3. When a user runs `tilt up` or `tilt down` with a list of resource names, "uncategorized" will often fail to give them the behavior they want. "uncategorized" objects always get applied on up and deleted on down, no matter which resources you specify. This means if you have resources Foo and Bar, and Foo depends on some FooConfigMap, `tilt up bar` will needlessly load `FooConfigMap`, or if you have both Foo and Bar running, `tilt down bar` will delete FooConfigMap, even though Foo still needs it!

**Comment by djcp** [comment]
persistentvolumes and persistentvolumeclaims show up as uncategorized too, and they are SUPER common for our use case to keep postgres, redis, and some file caches (e.g. ruby bundler) around.

**Comment by landism** [comment]
#2990 should help a lot with concerns #1 and #2 above.

**Comment by drubin** [comment]
We are having the same issue and its not just an annoying extra field in it actually causes our ingress server to throw errors.

This happens because tilt applies the ingress rules, but it doesn't have an svc/deployment/pod so the ingress controller (in this case traefik) gets a list of ingress rules and tries to match them to service but this doesn't work so it throws errors and spams the log output.

**Comment by ntfrnzn** [comment]
Custom Resources will fall into this uncategorized group as well.  At least for me, there are CRs that I want to inject separately from their controller and see as a distinct resource.

**Comment by jazzdan** [comment]
This is now available as the `objects` parameter on `k8s_resource`: https://docs.tilt.dev/api.html#api.k8s_resource

Let me know if this works for y'all!

**Comment by drubin** [comment]
@jazzdan how does this solve the ingress problem? Sorry I couldn't get this from the current doc. Is there maybe a small example that demos this?

**Comment by jazzdan** [comment]
@drubin I'm not super familiar with ingresses but you could group the ingress with the things it references like so:

```python
k8s_resource("myworkload", objects=[myingress, myotherservice])
```

This would configure a k8s_resource "myworkload" with any object named "myingress" and any object named "myotherservice" included or bundled with it. Just like how out of the box Tilt will bundle a deployment with the service that references it.

Then they _should_ be applied intelligently such that you don't have these dependency issues but I didn't test ingresses specifically. If you can try that and let me know if that works that'd be great, otherwise I can get some ingresses configured and try it myself.

**Comment by drubin** [comment]
@jazzdan it's documented here https://github.com/tilt-dev/tilt/issues/2989#issuecomment-601790055

If you have k8s enabled resources tilt only filters out pods and deployments not ingress so if you have an ingress controller it will throw errors about ingress being there and referencing none existing services/deployments... 

I assume this isn't hasn't been resolved then.

**Comment by jazzdan** [comment]
Hey @drubin, sorry for the late response. I took a pass at how I would make Tilt deploy a CRD + ingress. What do you think of this?

https://github.com/jazzdan/tilt-ingress-objects-example

**Comment by drubin** [comment]
Sorry for the even later reply but this doesn't seem to work.  @jazzdan 

Let's say I have 2 k8s resources (David, Dan) each with a deployment, service, ingress.

When I do `tilt up david`  tilt seems to still deploy `david` but also the ingress from `dan` so my ingress controller sees the ingress deployed but the service doesn't exist so it throws a bunch of warnings.

Not sure if that helps explain it, if not I will also produce an example folder.

**Comment by jazzdan** [comment]
@drubin yeah I think an example folder would be good, probably on a new issue. :)
