### ISSUE TITLE
When deleting yaml files, k8s_yaml should delete the related resources

### ISSUE THREAD

**Issue by rhyek** [tilt-dev/tilt#3137]
I might be missing something from the documentation, but couldn't find any related entries or github issues.

My current workflow is basically I am writing all my infrastructure as code with Pulumi with the option to output the build as yaml files during local development. Tilt is reading *some* of those yaml files using `k8s_yaml`. Whenever I delete a k8s resource within Pulumi and rebuild, the yaml file will be removed. I expect Tilt to handle this event and delete the corresponding resource from my cluster.

Currently I have to delete those resources manually using `kubectl` and this is not ideal.

**Comment by nicks** [comment]
Yes. I agree this is something we should do. We've talked about it a little in some other places (e.g. https://github.com/windmilleng/tilt/issues/3035). But this is a much better description of the problem I've heard in other places, so I'm going to leave this as the tracking ticket for this feature. Thanks for the request!

For now, one thing I've seen people do is `kubectl get deployments -l "app.kubernetes.io/managed-by=tilt"` (to get all the deployments that Tilt created, so that they can delete them)

**Comment by rhyek** [comment]
Thanks. In my case that workaround wouldn't work, because I still want to keep the other resources I didn't delete running.

Glad you're interested in the feature.

**Comment by milas** [comment]
As of v0.21.0, Tilt will clean up old K8s resources on Tiltfile update.

Please note that this only applies to resources Tilt previously deployed for the given `tilt up` invocation. That is, Tilt will NOT clean up resources it did not deploy or that it deployed from a _previous_ `tilt up` invocation at this time.
