### ISSUE TITLE
Feature request: Remote docker build in tilt

### ISSUE THREAD

**Issue by milindchawre** [tilt-dev/tilt#3398]
tilt works well for local development. But to build the docker image, docker is required locally on my workstation. Need a way to off load the docker build to a remote cluster, to save from slower builds and unnecessary work required to configure docker locally especially on windows machine.

**Comment by jazzdan** [comment]
Tilt has a custom_build Tiltfile function that lets you supply any image builder you want by supplying a shell script. So you can use this to build images with Bazel, or Kaniko, or whatever. See: https://docs.tilt.dev/custom_build.html

I've gotten remote Docker builds working using [docker buildx Kubernetes driver](https://medium.com/nttlabs/buildx-kubernetes-ad0fe59b0c64) like so:

```Tiltfile
custom_build(
  'gcr.io/tilt/stuff',
  'docker buildx build --platform=linux/amd64 -t $EXPECTED_REF --push .',
  ['Dockerfile', 'index.ts', 'package.json', 'yarn.lock', '.dockerignore'],
  skips_local_docker=True,
  disable_push=True,
)
```
We've been meaning to write up some docs on this, so I'll leave this issue open so we can track that work.

**Comment by milindchawre** [comment]
Great!
Thanks @jazzdan 
I don't found any doc and thought this feature is not available.
I will take a look at `custom_build`.

**Comment by joseph-zhong** [comment]
Following from discussion with @nicks, we agree this would be an incredibly useful enhancement -- in particular, since transitioning into WFH, with many people with very limited internet bandwidth it's been an important push to optimize our docker build sizes as much as possible, and minimize any transfers across the net.

Paying the cost anytime Tilt spuriously rebuilds and re-deploys with a full `docker push` can suddenly add 5-15min to development cycles, and is especially felt when syncing fails due to flaky internet.

That said, docker buildx is an alternative we had not yet looked into and looks very promising to start with (after looking into other alternatives such as Kaniko etc).

I'll let @rohinb2 comment further on thoughts and updates

**Comment by rohinb2** [comment]
The main con we see with buildx is it shares the entire build context with the builder each time. For large projects, this may not be suitable - it would be a lot faster to maintain a state of the project on the builder itself and send the relevant differences. We're experimenting with these ideas now, will keep you guys updated.

**Comment by nicks** [comment]
@rohinb2 re: "buildx shares the entire build context with the builder each time" - hmmm...are you sure? AFAIR, Docker Buildx now has a filesync protocol so that it can send the build context incrementally, see https://github.com/moby/moby/issues/31829

**Comment by rohinb2** [comment]
@nicks Huh, will look into it. We found it was taking a lot of time/bandwidth even when we didn't change anything. Thanks for the tip.

**Comment by nicks** [comment]
@rohinb2 I'm worried that there are still bugs in it to shake out, and it's falling back to sending the full build context for some reason! file-change-syncing is surprisingly hard to get right :grimacing:

**Comment by milindchawre** [comment]
Some file synchronization service like [syncthing](https://syncthing.net/) might help here.

**Comment by nicks** [comment]
Here are some docs on how to build remotely on a cluster:
https://blog.tilt.dev/2021/11/12/docker-build-alternatives.html
https://github.com/tilt-dev/tilt-example-builders#kubectl-build
