### ISSUE TITLE
k8s target infinitely rebuilding

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#3496]
Adam Fletcher from slack reports that he has k8s targets infinitely rebuilding in Tilt.

Pieces of information collected while debugging:
1. Tilt does not log why it's building the resource, which is a bug in itself
2. `tilt dump engine` shows the build reason as `0`, which would ideally never happen

Adam says this happens consistently on 0.15.0 and not on 0.14.3. I looked at `git log v0.15.0...v0.14.3` and the only commit that seemed like it might cause this was 0ada74b. I gave him a build with 0ada74b reverted and the bug still repro'd for him.

We're working on getting a repro he can hand off to us.

aside: it seems like at some point it'd be good to have `NextTargetToBuild` also return the reason, rather than recalculating it in a separate method

**Comment by KOGI** [comment]
**disclaimer**: I have no idea if this issue is actually related or not, but I've been working with them lately, so they came to mind)

Both the `git_resource` and `helm_remote` extensions can potentially cause this if their cache locations are not added to the top-level tiltignore. See the following documentation:
* helm_remote: [Usage](https://github.com/tilt-dev/tilt-extensions/tree/master/helm_remote#usage)
* git_resource: [Change the Cache Location](https://github.com/tilt-dev/tilt-extensions/tree/master/git_resource#change-the-cache-location)

**Comment by landism** [comment]
Thanks KOGI. IIUC, the situation you describe would have different symptoms: the build reason and log would indicate that the build is happening because a cache file changed.

In this case, we get no build reason and no log message indicating why the build is happening.

**Comment by landism** [comment]
#3505 fixed this
