### ISSUE TITLE
Tilt should understand Helm hooks

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#3658]
Helm charts have a concept of [hooks](https://helm.sh/docs/topics/charts_hooks/) that allow you to intervene at certain points during a chart's deploy cycle. From the docs, you can do things like:

* Load a ConfigMap or Secret during install before any other charts are loaded.
* Execute a Job to back up a database before installing a new chart, and then execute a second job after the upgrade in order to restore data.
* Run a Job before deleting a release to gracefully take a service out of rotation before removing it.

Tilt breaks this behavior because it uses `helm template` to get the YAML and disregards the annotations that are present on the resources that tell Helm in which order things should be deployed.

It would be cool if the `helm` built-in supported this behavior. In the process it might make sense to break the `helm` built in out in to its own extension.

Spun out of #3651

**Comment by nightscape** [comment]
I just got bitten badly by this but luckily found this issue:
I'm using https://github.com/GoogleCloudPlatform/spark-on-k8s-operator to set up a local Spark dev env with Tilt.
spark-on-k8s-operator defines a [`pre-delete` Helm hook that deletes the installed CRDs](https://github.com/helm/charts/blob/master/incubator/sparkoperator/templates/crd-cleanup-job.yaml).
As Tilt doesn't understand these hooks it runs the `pre-delete` job immediately, removing the CRDs.

Would it maybe be an option to use `helm template` to make Tilt understand what's inside a Helm chart, but run `helm install` to do the actual work?

**Comment by gnarea** [comment]
@jazzdan, I don't think the solution should be to try to emulate Helm. It should be to actually run `helm install` or `helmfile apply`. You're never going to be able to replicate it 100%, and even if you managed to do it at one point, your implementation will be obsolete again as Helm evolves.

I think Tilt should offer an option not to manage, but simply _observe_ Kubernetes resources managed by other tools like Helm or helmfile. And it should also be able to call `helm uninstall` as part of `tilt down`.

I'm new to Tilt, so please correct me if I'm wrong, but what I'm describing above can't be implemented in an extension without changing Tilt itself, right?

**Comment by vkruoso** [comment]
This is really painful in situations where you are developing your own chart, and changes some resource name for instance, or simply delete something. Because of the `helm template` pattern tilt does not remember previous objects that would need to be removed. 

To work correctly on a case like this, either tilt would need to keep state between applies, or inject some labels on the objects to be able to identify them later. But that does not solve all the hooks and other things helm does.

The other approach said by @gnarea: apply the chart using `helm` itself, but have a way to identify all objects deployed, and change them the way it is done by tilt now. This will probably face some issues with stuff that is immutable tough, but being in a dev environment is better on cases like this: delete + create.

I think Helm is very important to the ecosystem now, so this becomes very relevant to the dev experience. Tilt is awesome and we can work around most of those points doing some manual steps.

**Comment by nicks** [comment]
`helm_resource` should support this because it uses `helm install` directly: https://github.com/tilt-dev/tilt-extensions/tree/master/helm_resource

So I'm going to close this issue.
