### ISSUE TITLE
Force docker build for unused images

### ISSUE THREAD

**Issue by emaincourt** [tilt-dev/tilt#3679]
Hi folks 👋

First of all thanks for the great work you've done with Tilt ! I've been playing around with it over the past days and can already see potentially huge improvements in our local development processes.

However, I noticed that Tilt does not build images that are not explicitely refered by a Kubernetes standard resource. In our case, we use Argo CRDs which allow to define Workflows. Each workflow only consists of one or multiple steps that run a given image with parameters. Therefore we need to build these images. Please find an example [here](https://github.com/argoproj/argo/blob/master/examples/steps.yaml). As the images are not typically attached to a vanilla Kubernetes resource, it seems that Tilt ignores it.

Please let me know if I'm wrong and I only missed the documentation part about force building an image. Otherwise, would you have any hints or suggestions ? In case it requires implementing new stuff, I would be more than glad to take care of it of course.

Thanks for reading

**Comment by nicks** [comment]
Thanks for the kind words ☺️

Usually you'd configure tilt to know where to find the image in your config, so that it can do the image injection and build ordering correctly. Here's a guide on how to do that:
https://docs.tilt.dev/custom_resource.html

In your case, I _think_ it'd look something like
k8s_kind('Workflow", image_json_path='{.spec.templates[*].container.image}')

Tho I can try to test it with a real example later this week (I think we have an Argo docs request somewhere)

**Comment by emaincourt** [comment]
@nicks Thanks for the quick answer. Your link and example seem to perfectly match my case. I'm sincerely sorry I couldn't find it by myself. Closing ☀️
