### ISSUE TITLE
high cpu usage with many logs

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3936]
When you have lots of logs, Safari consumes a lot of CPU. Repro steps:
1) update tilt-example-go to log every 1ms or 10ms
2) tilt up
3) leave the browser tab open for a while

TBH, i think the way we're handling log rendering with React is actually the wrong approach, and is giving us much worse render performance than something like xterm.js - React's render loop is simply not well-suited for append-only logs. Though there might be other things we should be doing w/r/t log GC client-side

**Comment by maiamcc** [comment]
Is this related to #3359 or distinct?

**Comment by nicks** [comment]
In that ticket, Andy is talking about page load times, where this is about steady-state

**Comment by mikecsmith** [comment]
I'm also seeing this in a microservice setup with Tilt running _c.__ 20 services. One service I've been developing against is taking 20mins plus to fully load logs into the UI on a new Tilt up and I'm hitting very high CPU usage.

**Comment by milas** [comment]
The log renderer was completely rearchitected in #4033 for the new UI using an approach as described in the issue.

There are several other recent improvements to log rendering on the client for performance, most notably #4215 which will cap the client logs to prevent browser tabs from getting locked up due to excessive memory usage from high log volume. (This will be available in the next Tilt release, i.e. > 0.18.9.)

There's also a manual clear logs button from #4170 that can help.

Please feel free to comment additionally here or open a new issue if you continue to see log performance issues!
