### ISSUE TITLE
Zoom into logs for effectively larger font size

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#4210]
## Describe the Feature You Want

Font size is too small for some folks. There should be a way to zoom.

### Current Behavior

Just one font size

### Why Do You Want This?

**Additional context**

**Comment by markgarrigan** [comment]
Could you just zoom with your browser? Maybe not ideal. But it "works".

I'd like the left column be resizable.

Not zoomed...
![Screen Shot 2021-02-17 at 1 31 34 PM](https://user-images.githubusercontent.com/422391/108257530-8b042c80-7124-11eb-99df-adf7c306ea31.png)

zoomed...
![Screen Shot 2021-02-17 at 1 31 52 PM](https://user-images.githubusercontent.com/422391/108257578-99524880-7124-11eb-9b1e-615b79b02e4c.png)

**Comment by jeremykay** [comment]
Zooming in browser for me is less ideal because it makes the left side nav much larger, but has less of an effect on the logs. This also works less well for smaller screens.

The text size also was fine for me in previous versions before the UI refresh, so this has been a small (pun intended) downgrade.

**Comment by nicks** [comment]
this is out in v0.19.1!
