### ISSUE TITLE
allow_k8s_contexts() not enforced when using k8s_yaml()

### ISSUE THREAD

**Issue by bitfactory-henno-schooljan** [tilt-dev/tilt#4234]
### Expected Behavior
`k8s_yaml()` should respect the allowed contexts setting, just like it does with `local()` calls.

### Current Behavior
`k8s_yaml()` does not respect the allowed contexts setting, for example if I run this:

```
allow_k8s_contexts('allowed-context')
k8s_yaml(helm('path/to/chart'))
```

It installs the chart on the current context no matter what it is, such as remote GKE contexts.

#### `tilt doctor` Output
```
Tilt: v0.18.10, built 2021-02-19
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: gke
- Context: gke_bf-k8s-development_europe-west4-b_development-gke-development
- Cluster Name: gke_bf-k8s-development_europe-west4-b_development-gke-development
- Namespace: default
- Container Runtime: containerd
- Version: v1.18.15-gke.1100
- Cluster Local Registry: none
```

#### About Your Use Case
I want to prevent applying YAML to the wrong cluster, but it looks like this is not being enforced when using `k8s_yaml()`.

**Comment by maiamcc** [comment]
To be clear, `allow_k8s_contexts` doesn't SET the context, it will just prevent certain contexts from throwing an "oh no, did you really mean to use the context?!" error [see docs](https://docs.tilt.dev/api.html#api.allow_k8s_contexts).

That said, if you don't list `gke_bf-k8s-development_europe-west4-b_development-gke-development` as an allowed context somewhere, your Tiltfile ought to throw an error like:
```
ERROR: Stop! gke_bf-k8s-development_europe-west4-b_development-gke-development might be production.
If you're sure you want to deploy there, add:
allow_k8s_contexts('gke_bf-k8s-development_europe-west4-b_development-gke-development')
to your Tiltfile. Otherwise, switch k8s contexts and restart Tilt.
```
Are you seeing this error anywhere?

Could you try running [this sample Tiltfile](https://gist.github.com/maiamcc/dc198b2cd4eafde8be9c8b91a689df20) while in your GKE cluster--verify that the cluster name it prints is correct, and that it throws a "might be production" error instead of applying any YAML

**Comment by maiamcc** [comment]
Wait, never mind, I think I know what's going on--we (foolishly) only double check your k8s context if there are PODS being created. That's a bug on our end, I'll fix it!
