### ISSUE TITLE
resources that trigger on file change but don't auto-init

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4275]
`auto_init=False` is currently only compatible with `TRIGGER_MODE_MANUAL`. I've heard of use-cases where you want resources that DON'T auto-init, but only trigger on file change.

I'm filing this feature request to help collect these use-cases. Please comment below if you have one!

**Comment by markgarrigan** [comment]
If someone knows a way to get an Angular app or other HTML/JS/CSS app live reloading in the browser when the files change then compile in a Pod on a K8s cluster, then I'm all ears.

However, in our case...

The Angular app is being served up on http://localhost:8080 in the container. Then there is an ingress on the cluster that proxies calls from https://my-nice-dev.domain/app-name to the K8s service that points to the running pod.

```
ingress.yaml (truncated)
...
spec:
  rules:
  - host: my-nice-dev.domain
    http:
      - path: /app-name/?(.*)
        backend:
          serviceName: <app-service>
          servicePort: <app-service-port>
...
```

There's no way, that I can see, and have tried, to get the web socket that Angular creates for live reloading to be served from http://localhost:8080/app-name without changing where the Angular app is served from. It needs to be served from http://localhost:8080/app-name but that will break my ingress rule. If the web socket is not served from /app-name then it tries to connect to ws://my-nice-dev.domain/socketjs. This doesn't work because that path doesn't exist in the ingress. I "could" figure out a way to proxy that call as well, however, we have multiple apps running that would each need to be live reloaded. I can't see a way where it would know how to route the traffic to multiple apps.

Also... http to https is an issue with websockets. I'd have to host the angular app from https://localhost:8080 which opens up a whole other can of worms.

Anyway... after that super long confusing description here's what I came up with...

I created my own live-reload service that runs in the cluster and is accessible at https://my-nice-dev.domain/live-reload

The service opens a Server Side Event stream. When an app is loaded in the browser it makes a connection to GET /live-reload/app-name. This is nice because I don't care about the host since ingress is handling the routing. Now the frontend app is waiting for messages from the server. If I send a POST to https://my-nice-dev.domain/live-reload/app-name the server sends out a message to all subscribers telling them which app needs to be refreshed in the browser.

This works well, except I have to trigger the POST manually. I'd like it to run the same way that the run() function does after a sync() in live_update.

In the code below.. the update.js file has the code to do the POST. I could remove that and it could just be a curl command right in the Tiltfile.

```
load('../dss-common/tilt/Config', 'dss_namespace')

custom_build(
  'cfg-app-container',
  '../dss-common/tilt/kaniko.sh cfg-app Dockerfile.dev',
  ['.'],
  live_update = [
    sync('./src', '/usr/app/src'),
    sync('./angular.json', '/usr/app/angular.json'),
    sync('./package.json', '/usr/app/package.json'),
    sync('./package-lock.json', '/usr/app/package-lock.json'),
    run('cd /usr/app && npm install', trigger=['./package.json', './package-lock.json'])
  ],
  skips_local_docker = True
)

local_resource('cfg-app-live-reload', cmd='node ../dss-live-reload/update.js', env={'APP': 'cfg-app', 'DOMAIN': dss_namespace}, trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False)

k8s_yaml(helm('helm/cfg-app', set=['image=cfg-app-container'], namespace=dss_namespace))

k8s_resource(workload='cfg-app', resource_deps=['cfg-api'])
```

Hope that makes sense... I basically just spewed out everything on the page. Questions are welcome! :)

**Comment by markgarrigan** [comment]
Writing it out got me thinking. I guess I should/could run `node update.js` in the cluster since dss-live-reload is managed by Tilt. However, same ish issue... Can I run a command in another Pod from inside the live_update?

I "could" add update.js to each apps container. However, there's already a running process on those containers (http server) does the run method start a new process?

**Comment by markgarrigan** [comment]
Basically... something like this...

```
custom_build(
  'cfg-app-container',
  '../dss-common/tilt/kaniko.sh cfg-app Dockerfile.dev',
  ['.'],
  live_update = [
    sync('./src', '/usr/app/src'),
    sync('./angular.json', '/usr/app/angular.json'),
    sync('./package.json', '/usr/app/package.json'),
    sync('./package-lock.json', '/usr/app/package-lock.json'),
    run('cd /usr/app && npm install', trigger=['./package.json', './package-lock.json']),
    run_resource('dss-live-reload', cmd='node update.js', env={'APP': 'cfg-app', 'DOMAIN': dss_namespace}, trigger=['./src'])
  ],
  skips_local_docker = True
)
```

**Comment by markgarrigan** [comment]
I moved the update.js file to Angular app. And this is working nicely. Not sure if it's the best. But it feels ok. Sort of like having to install any other live-reload script into the app with npm. So, not too bad.

```
custom_build(
  'cfg-app-container',
  '../dss-common/tilt/kaniko.sh cfg-app Dockerfile.dev',
  ['.'],
  live_update = [
    sync('./src', '/usr/app/src'),
    sync('./angular.json', '/usr/app/angular.json'),
    sync('./package.json', '/usr/app/package.json'),
    sync('./package-lock.json', '/usr/app/package-lock.json'),
    run('cd /usr/app && npm install', trigger=['./package.json', './package-lock.json']),
    run('cd /usr/app && APP=cfg-app DOMAIN=' + dss_namespace + ' node update.js', trigger=['./src'])
  ],
  skips_local_docker = True
)
```

**Comment by nicks** [comment]
lol, i was just writing a comment to suggest something like this but i had to delete it!

i wonder if we should add working directory and env params to `run`... :thinking:

**Comment by nicks** [comment]
alternatively, add a `local_run` for the use-case that you described in the comment above, in case you can't get the update.js inside the container

**Comment by markgarrigan** [comment]
Right.. either way would be nice. Yeah.. getting rid of the `cd` would be nice.

**Comment by markgarrigan** [comment]
And also passing ENV vars in a parameter if possible. But the way I have it is also fine with me.

**Comment by markgarrigan** [comment]
I moved the update script to an NPM package. Then added an NPM Script that I can run from Tilt. So now it feels a little better. More integrated with the app.

load('../dss-common/tilt/Config', 'dss_namespace')

custom_build(
  'cfg-app-container',
  '../dss-common/tilt/kaniko.sh cfg-app Dockerfile.dev',
  ['.'],
  live_update = [
    sync('./src', '/usr/app/src'),
    sync('./angular.json', '/usr/app/angular.json'),
    sync('./package.json', '/usr/app/package.json'),
    sync('./package-lock.json', '/usr/app/package-lock.json'),
    run('cd /usr/app && npm install', trigger=['./package.json', './package-lock.json']),
    run('cd /usr/app && npm run reload --silent -- --app=cfg-app --domain=' + dss_namespace, trigger=['./src'])
  ],
  skips_local_docker = True
)

k8s_yaml(helm('helm/cfg-app', set=['image=cfg-app-container'], namespace=dss_namespace))

k8s_resource(workload='cfg-app', resource_deps=['cfg-api'])

**Comment by milas** [comment]
This is possible in v0.19.1+ (see #4292)!
