### ISSUE TITLE
tilt up uses more than default port

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4282]
### Expected Behavior

`tilt up` by default should grab port 10350 alone.

### Current Behavior

`tilt up` grabs port 10350-10352.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.18.11, built 2021-02-26
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:55003
- Version: 1.41
- Builder: 2
---
Docker (local)
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: is
- Container Runtime: docker
- Version: v1.20.2
- Cluster Local Registry: none
...
```

**Comment by landism** [comment]
Is it possible your Tiltfile defines some port forwards on those ports? I've not had any luck reproducing this or finding any code in Tilt that might do this.

**Comment by landism** [comment]
Ah, it looks like the experimental metrics feature uses ports 10351 and ports 10352, with no configurability.

We should fix this so that enabling metrics doesn't prevent you from running multiple Tilts.
In the meantime, you can leave metrics enabled for one instance, but need to have it disabled for all others.

Unfortunately, we don't yet have docs for this experimental feature.
If you don't particularly care about the feature, you can just disable it in the UI to get rid of it everywhere.
If you want to keep it enabled for one instance of Tilt, you can set the env var `TILT_METRICS=local` when running Tilt, or put `experimental_metrics_settings(enabled=True)` in its Tiltfile.

**Comment by kevin-lindsay-1** [comment]
This issue does not appear to be present in newer versions.
