### ISSUE TITLE
Overriding imagePullPolicy in CRDs with tilt-managed images

### ISSUE THREAD

**Issue by Gibstick** [tilt-dev/tilt#4291]
I've presented this as a bug/oversight but maybe it was never implemented? Sorry if this is actually a feature request in disguise.

### Expected Behavior
When I use `k8s_kind` on a CRD with images, I want to specify `imagePullPolicy: Always` in my manifests and have Tilt override it when it manages the build so that I can both

1. always pull the latest image if I don't need to work on that image
2. have Tilt manage the build and use my local code changes.

That is, it should work the same way as images being built for normal TIlt resources (eg. pods from deployments).

### Current Behavior
Tilt is not overriding the `imagePullPolicy` of my CRDs and is failing with

```
ImagePullBackOff: Back-off pulling image "foo.bar/baz/helloworld:tilt-4a9902d1db2b9157"
```

even when I am specifying a `docker_build` for it. It looks like tilt knows enough to override the image name, but not enough to override the imagePullPolicy, which is what makes me think this is an oversight/bug.

### Steps to Reproduce

1. Use `k8s_kind` with an `image_json_path` to a CRD that has images. For example, https://github.com/tilt-dev/tilt/issues/3045#issuecomment-785155248
2. Add a `docker_build` for the image
3. `tilt up` and for this use case, trigger an argo workflow with this image

#### `tilt doctor` Output

```
Tilt: v0.18.9, built 2021-02-12
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://192.168.64.3:2376
- Version: 1.41
- Builder: 2
---
Docker (local)
- Host: Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: local
- Container Runtime: docker
- Version: v1.20.2
- Cluster Local Registry: none
---

```

#### About Your Use Case

Our use case is being able to use Tilt to manage both our "services" (normal deployments that create pods) and our "steps" (argo workflow steps) in the same way, without having to resort to workarounds or remembering to manually pull.

**Comment by landism** [comment]
Thanks for the report!

We should definitely have Tilt be a bit smarter about fixing pull policies on CRDs for simple cases like this.

In case you're curious about what's going on:
Tilt does pull policy overriding by searching the k8s api struct for instances of 'Container', and for any it finds, changing their 'ImagePullPolicy'. Since CRDs are custom, the k8s api basically just gives them to you as untyped json, so there are no 'Container's to fid. Even if we did have typed data, some CRDs have image names but don't use the 'Container' spec or have any 'ImagePullPolicy' field at all. The first couple CRDs we tested with this feature were like this, so it didn't come up.

I'll looking into changing TIlt so that if the user specifies an image_json_path and that element has a sibling named 'imagePullPolicy', Tilt just changes it.

In the meantime, if you want, you can work around this by modifying the yaml in your Tiltfile before passing it to `k8s_yaml`, e.g.:
```
j = load_yaml('crd.yml')
j['spec']['templates'][0]['container']['imagePullPolicy'] = 'IfNotPresent'
k8s_yaml(encode_yaml(j))
```

**Comment by Gibstick** [comment]
Great, thanks. Just to spell it out,, more for my purposes and maybe someone else who comes across this, we're using kustomize so our workaround would look something like:

1. `kustomize(...)`
2. `decode_yaml(...)`
3.  Programmatically traverse that object, find our CRDs, and override the imagePullPolicy just like above
4. `encode_yaml(...)`
5. `k8s_yaml(...)`

It's kinda involved but it should work. I'll report back if I manage to try it.
