### ISSUE TITLE
Please add first class Helm support that enables Helm install with real releases

### ISSUE THREAD

**Issue by dmusicant-dk** [tilt-dev/tilt#4375]
## Describe the Feature You Want

I should be able to deploy a helm chart with Tilt and have it create a real helm release rather than just using the `helm template` call and deploying YAMLs. i.e. I should be able to run `helm list` and see my release.

### Current Behavior

Tilt simply runs `helm template` and deploys YAMLs meaning I lose the true use and benefits of helm.

### Why Do You Want This?

I want to be able to test helm installs locally while still using Tilt to manage the orchestration and chained dependencies of everything (such as building images). I should be able to use it to also run helm tests and rollbacks and upgrades, and helm hooks.

**Additional context**
none

**Comment by nicks** [comment]
Thanks for the request! 

AFAIK, there's not really a good way for Tilt and Helm to interoperate with `helm install` (since tilt needs to inject its own image and registry names to work correctly). This may not be technically feasible to implement without linking in Helm's deployer directly.

Related issues:
https://github.com/tilt-dev/tilt/issues/3658
https://github.com/tilt-dev/tilt/issues/3030

**Comment by dmusicant-dk** [comment]
@nicks Can you explain a bit more about the Tilt image and registry names that it needs to inject? Helm charts are just gzipped files, can't you add a YAML inside the chart (and repackage) to also include the Tilt stuff? Or are you referring to something else?

**Comment by nicks** [comment]
@dmusicant-dk Sure!

If you look at the Skaffold docs, they require some extra configuration so that Skaffold can find the image in the Helm chart (see the big "IMPORTANT" note in the skaffold docs)

Tilt does lots of other things as well that Skaffold doesn't do, so needs to be able to see the rendered yaml, as well as get the UIDs of what Helm deploys (which are not easily accessible)

To be clear, this is only really necessary if you're using Tilt to edit the image in the chart. If you just want to install an image that you're not editing, you can do something like `local_resource('redis', 'helm install redis')`

**Comment by steve-bitdotio** [comment]
+1 to this issue.

Having "real" helm releases would help with labeling/naming versioned workloads, i.e. database migrations that need to happen every every release via a job, etc.

**Comment by adamf** [comment]
+1 to this - would be very helpful for us!

**Comment by ToonvanStrijp** [comment]
@nicks I was thinking about this a lot and stumbled upon this option `--post-renderer`. The [documentation](https://helm.sh/docs/topics/advanced/#usage) page of Helm explains that this flag can be used to point to an executable that reads the STDIN (the rendered yaml files) and returns the modified yaml files (tilt magic and injecting the right image tags etc) to the STDOUT.

I'm not sure there is a way to make this work with tilt but from what I can read in their documentation this seems like a good fit. That way helm still handels the "real" installation, but you would still have the benefits of tilt!

**Comment by nicks** [comment]
We now have `helm_resource`, an extension for installing natively with Helm.

https://github.com/tilt-dev/tilt-extensions/tree/master/helm_resource

We're still updating the docs and writing some blog posts about it, but we expect it to gradually replace the approach that the `helm()` function uses.
