### ISSUE TITLE
better support for long resource names

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4614]
## Describe the Feature You Want
Better support for long resource names in the UI

### Current Behavior
The names get cut off, with no way to expand them

### Why Do You Want This?
Kubernetes resources tend to use prefixes heavily. For example, many Helm charts prefix every resource in the chart with the same name.

This makes the sidebar display kind of useless, because all sidebar items have the same name.

**Additional context**
Related issue (choosing custom icons):
https://github.com/tilt-dev/tilt/issues/3530

Note that you can also use k8s_resource(new_name=) to rename a resource manually

**Comment by hyu** [comment]
A user also brought this up during a user interview on 3/8/21:

"...the little pane of where the logs generated from? I need that to be resizeable. It's too small. So it cuts off everything, and where the log source from I don't really know."... "The names of my services come from Helm charts. So they're all like, 'prefix-something-something-something-chart.' Super hard to read these."

Interviewer: "What if you could see the full name of a resource, and the trade-off is that it basically makes them taller and pushes stuff down?"

" Yeah, or just shrink the font size. I mean, I had a custom style sheet for a while that just shrank the font size. The resource names don't change often enough for me to need them to be very readable."

**Comment by nicks** [comment]
i played around with some ideas around displaying common prefixes, it looks like this:

![Screenshot from 2021-06-09 19-41-08](https://user-images.githubusercontent.com/278641/121443024-b7a1b580-c95a-11eb-8b50-b1e6aa1ed9a8.png)
![Screenshot from 2021-06-09 19-38-01](https://user-images.githubusercontent.com/278641/121443025-b83a4c00-c95a-11eb-9924-9d3258aaf819.png)

**Comment by hyu** [comment]
I think we should allow users to resize the sidebar. Kind of like in VS Code, how you can make the sidebar as wide as you want. Even absurdly wide, like so:

<img width="1680" alt="Screen Shot 2021-06-14 at 12 58 46 PM" src="https://user-images.githubusercontent.com/20349/121930402-5427d700-cd10-11eb-8cbc-c9d257e8d634.png">

@nicks, thanks for posting the idea of adding the prefix. My main concern with this design is that the text will be very small and possibly not legible because of the low contrast, and may contribute to a cluttered appearance for this card (which Surbhi and I have been trying to simplify)

**Comment by SurbhiSGupta** [comment]
I agree with @hyu that the best option would be to make the sidebar stretchable - either with or without prefix - because:
- Long names can get even longer and splitting the name with a prefix alone, may not be sufficient
- How is the prefix decided? How long can it be?
- The card size looks very busy with an added field, especially in the sidebar

Here is a quick view of all the various options..

![2021-06-10 Truncated name options for sidebar](https://user-images.githubusercontent.com/46793797/121932943-7111d980-cd13-11eb-9871-ce3895b4d8ae.gif)

**Comment by nicks** [comment]
Ya, we will probably end up having to do both.

The VSCode example is an illustrative one - note that VSCode only shows the base filename, not the absolute file path. It's the same problem here - if you show the full name, you will end up having to repeat redundant information a lot.

**Comment by nicks** [comment]
@SurbhiSGupta - re: "how is the prefix decided" - the experiment i was playing around with tried to infer them using "-" as a separator. Resource grouping might help solve this problem - I would expect all resources in a group to have a common prefix.
