### ISSUE TITLE
tilt rarely fails on launch with "Error: error creating builder: informer has already started"

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4698]
### Current Behavior
Occasionally Tilt fails on startup with the output "Error: error creating builder: informer has already started"

### Steps to Reproduce
Tiltfile:
```
local_resource('hi', serve_cmd='while true; do sleep 1; done')
```
repro.sh:
```
#!/bin/bash

RUN_COUNT=0
REPRO_COUNT=0
while true
do
  RUN_COUNT=$((RUN_COUNT + 1))
  OUTPUT="$(tilt ci 2>&1)"
  if [[ "$OUTPUT" == *"already started"* ]]
  then
    REPRO_COUNT=$((REPRO_COUNT + 1))
    # echo "$OUTPUT"
  fi
  echo "${REPRO_COUNT}/${RUN_COUNT} repros"
done
```

This has been getting me 5-ish repros in the first 100 runs.

### Context
This is using a Tilt built from master at 77c58543.
The error is from [this line](https://github.com/tilt-dev/tilt/blob/ae74dafaf1d2f0ef5f563e985d45d4166c4766b6/internal/controllers/builder.go#L56) from #4682, which was apparently aimed specifically at solving the problem of the informer starting too soon.

I haven't tried to examine the extent to which this repro is contrived (like maybe it only happens if you start a new tilt right after killing an old one), but I did initially encounter this error during normal usage.

**Comment by milas** [comment]
For context/future debugging, the init sequence here has gone through several iterations as we've uncovered race & dependency issues.

One of the complicating factors is that to **construct** (but not start!) the controller-runtime `manager.Manager`, it needs to connect to the API server. As part of constructing the manager, it also creates the `ctrlclient.Client` which is needed by every reconciler (and others, such as the store subscribers that help with migration). Due to the fact that the apiserver gets initialized by the store setup, the controller manager must do the same, and we have a `DeferredClient` implementation which will return errors until provided with a real implementation.

The reconciler/controllers need to initialize themselves using the manager as well using a builder pattern, and as part of this they set up local field indexes on the `Indexer` as part of the cache, but this will fail if the `Indexer` is already running.

As a result, the flow is:
* Start apiserver (via store subscriber `SetUp`)
* Construct controller-runtime `manager.Manager`
* Construct all reconciler `builder.Builder`s
* Complete/finalize all reconciler `builder.Builder`s
* Start controller-runtime `manager.Manager`

There is one remaining flaw here which is that starting the controller-runtime `manager.Manager` is asynchronous and includes initializing the cache - calls to the client can start before the cache is initialized and will receive errors, but there's no way for us to block until the cache is ready. This is less of an issue now with #4669 (which just suppresses the errors) and #4670 (which allows store subscribers to retry, similar to the reconcilers, instead of fatally erroring)
