### ISSUE TITLE
"not a known field selector" error on startup

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4719]
Example from a recent CI failure:
```
[0] controller.kubernetesdiscovery "Reconciler error"
  error="failed to fetch managed PodLogStream objects for KubernetesDiscovery fe: \".metadata.controller\" is not a known field selector: only \"metadata.name\", \"metadata.namespace\""
  name="fe"
  namespace=""
  "reconciler group"="tilt.dev"
  "reconciler kind"="KubernetesDiscovery"
```

This means the `List()` is using the real client, not the cache/indexer. This shouldn't really be possible: https://github.com/kubernetes-sigs/controller-runtime/blob/985e819db7af1cd17782ca7ad27644d0ca655054/pkg/client/split.go#L102-L121

**Comment by nicks** [comment]
The problem is that we turned of caching in the tests. This makes the tests perform much better, but means we bypass the indexer.
https://github.com/tilt-dev/tilt/blob/master/internal/engine/upper_test.go#L3909

I'm not totally sure what the right way to fix this is, though I can spitball a couple ideas around

1) Maybe we shouldn't use the cache indexer at all. Instead, we'd list all the objects and have some helpers that filter out the ones we don't need. This should be pretty performant when running against the cache and when running against a small number of objects in tests.

2) Maybe we could index owner controllers on the apiserver rather than in the cache. This is architecturally simpler, but is inconsistent with how Kubernetes works in general. So we have to offset the benefits of that simplicity against the costs of inconsistency with what other k8s tooling expects.

3) Turn caching back on in the tests for objects that need it.

4) Use labels instead of Owner References for indexing. This is architecturally simple as well, but introduces some redundancy. We already do this for objects that aren't in the apiserver yet (like LocalResource(serve_cmd) and the Tiltfile)

I'm probably leaning towards (4), just because it's a known pattern that we use already.

**Comment by nicks** [comment]
I ended up going with approach (1). it was slightly less straightforward than (4), but there are some restrictions on labels that make (4) a bit tricky in practice.
