### ISSUE TITLE
support docker proxy configuration

### ISSUE THREAD

**Issue by lizzthabet** [tilt-dev/tilt#4878]
## Describe the Feature You Want
With the Docker CLI/client, you can create a `~/.docker/config.json` file and specify [global proxy options](https://docs.docker.com/network/proxy/#configure-the-docker-client). These options should be parsed and respected by Tilt.

From [Roger Collins in k8s slack](https://kubernetes.slack.com/archives/CESBL84MV/p1629739294249500):
> [O]ur docker build processes rely on `http_proxy` being set in the environment to get through our proxy server.  This works as expected in my project folder doing `docker build` but `tilt up` doesn't seem to forward that env variable[.]

### Current Behavior
Proxy variables have to be manually specified as build arguments in `docker_build` within the `Tiltfile`.

### Why Do You Want This?

**Additional context**
This seems like it's related to other Docker CLI/client library discrepancies, like #4769 and #4607.

**Comment by milas** [comment]
Some extra context from debugging with @lizzthabet: the `config.json` proxy options get passed as build args. Those are treated specially and _don't_ have to be defined with `ARG` in the `Dockerfile` to get populated, you can test this out:
```bash
$ printf 'FROM busybox\nRUN env\n' | docker build --progress=plain --no-cache --build-arg "FOO=BAR" --build-arg "http_proxy=http://localhost" -
...
#5 [2/2] RUN env
#5 sha256:31a8fae1f67fb48dfd72545f54c006fbf75ca6e41fbbbbddc6e82e966e02c541
#5 2.413 SHLVL=1
#5 2.413 HOME=/root
#5 2.413 http_proxy=http://localhost
#5 2.413 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#5 2.413 PWD=/
#5 2.413 HTTP_PROXY=http://localhost
```
Neither `http_proxy` nor `FOO` were defined with `ARG` in the `Dockerfile` input, but notice that `http_proxy` (+ `HTTP_PROXY`) were populated while `FOO` was not due to the special handling.

Proxy variables from config: https://github.com/docker/cli/blob/25eee83d6b8c475548254b2decc9c8e0490d229c/cli/config/configfile/file.go#L233

Merged with user-specified build args: https://github.com/docker/cli/blob/25eee83d6b8c475548254b2decc9c8e0490d229c/cli/command/image/build.go#L601

A workaround for now is to explicitly specify the build arg when calling `docker_build`:
```python
build_args = {}
if os.getenv('TILT_HTTP_PROXY'):
  build_args['http_proxy'] = os.environ['TILT_HTTP_PROXY']

docker_build('myimage', context='.', build_args=build_args)
```
