### ISSUE TITLE
Building using base image dependency when the base image has variable name

### ISSUE THREAD

**Issue by brianbolt** [tilt-dev/tilt#5045]
### Expected Behavior
I would expect that dependent builds would work such that you could use BUILD_ARGS to resolve the FROM image dependency.

### Current Behavior
BUILD_ARGS seem to be ignored when matching Tilt dependencies

### Steps to Reproduce

I attempted something similar to the example below:

Tilt
```
BASE_NAME='test'
docker_build('example.com/{base_name}'.format(base_name=BASE_NAME), '.', dockerfile='Dockerfile.base')

docker_build('myapp', '.', dockerfile='Dockerfile.app', build_args={'base_name': BASE_NAME})

k8s_yaml('deploy.yaml')
k8s_resource('myapp')
```

Dockerfile.app

```
ARG repo=example.com
ARG base_name=notused-default
FROM ${repo}/${base_name}
```

The result was that myapp did not use the BUILD_ARG and therefore it did not use the Docker.base built image.

#### `tilt doctor` Output
```
Tilt: v0.22.10, built 2021-09-24
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: gke
- Context: asdfasdf
- Cluster Name: asdfasdf
- Namespace: asdfasdf
- Container Runtime: containerd
- Version: v1.20.10-gke.301
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
asdfasdf
```

#### About Your Use Case
Trying to achieve depedent builds

**Comment by hyu** [comment]
Hi @brianbolt,

I tried to repo your scenario using our sample project, tilt-example-nodejs. I added a `base_name` build arg in the [Tiltfile](https://github.com/tilt-dev/tilt-example-nodejs/blob/hyu/test-build-args/3-recommended/Tiltfile#L20), then referenced this in the [Dockerfile](https://github.com/tilt-dev/tilt-example-nodejs/blob/hyu/test-build-args/3-recommended/Dockerfile#L4). It's a bit contrived since the base image here is node:10. But, I tested this and the build_arg appears to be properly used.

Is this a correct repro of your situation?

Also, I'm curious to better understand your use case. Why do you want to have your base name as a variable in the Tiltfile, which you're passing through to the Dockerfile via build_args? You're trying to create a shared base image for multiple services to optimize your app build process, but sometimes you need to make changes on-the-fly to your base image? I'm interested to know more about the circumstances that led to this solution!

**Comment by brianbolt** [comment]
Thanks for follow up.  

I forked your tilt-example-nodejs repo to demonstrate the underlying issue.  

If you checkout master of [this repo](https://github.com/boltengineered/tilt-example-nodejs), run `tilt up`, you will see it fail.  If you then open Dockerfile2 and comment in the 1st line and comment out the second line, then it works.  This demonstrates our main issue that the build_args are not used to determine a base_image dependency.  i.e. its essentially needs to be a hardcoded match in the ref of the base docker_build and the FROM of the dependent Dockerfile.

Some more details:
The `base_name` variable in the [Tiltfile](https://github.com/boltengineered/tilt-example-nodejs/blob/master/3-recommended/Tiltfile) is used as part of ref for the first build, its then used again in the second build as a build_arg such that if resolved correctly, the FROM in [Dockerfile2](https://github.com/boltengineered/tilt-example-nodejs/blob/master/3-recommended/Dockerfile2) should match and make it the base build for the second ref `example-nodejs-image2`

The use case that we often configure a project to push to different areas of our docker repos depending on some variables passed in at runtime.  

e.g. `gcr.io/someslug/{project}/image' where the project is configured differently depending on deployment and development/production.

**Comment by milas** [comment]
Thanks for the bug report! This will be fixed in the next Tilt release
