### ISSUE TITLE
`KubernetesApply` "not found" race condition

### ISSUE THREAD

**Issue by lizzthabet** [tilt-dev/tilt#5125]
### Current Behavior

When implementing the `DisableSpec` + `DisableStatus` logic in `KubernetesApply` (#5077), I encountered a race condition in [`ForceApply`](https://github.com/tilt-dev/tilt/blob/master/internal/controllers/core/kubernetesapply/reconciler.go#L251-L255) between the engine building the k8s resource and the apiserver creating the k8s object.

If I try to get the `KubernetesApply` object before the `forceApplyHelper` runs, the code will consistently error out, saying that the resource cannot be found. I was able to reproduce this consistently in the [`TestConfigMap` integration test](https://github.com/tilt-dev/tilt/blob/master/integration/configmap_test.go), as well as by `tilt up`ing the `Tiltfile` in that test file.

This isn't a bug that's user-facing, as far as I can tell.

### Steps to Reproduce
To hit the race condition failure:
1. Move the `KubernetesApply` `Get` above the `forceApplyHelper` call.
```go
func (r *Reconciler) ForceApply(
	ctx context.Context,
	nn types.NamespacedName,
	spec v1alpha1.KubernetesApplySpec,
	imageMaps map[types.NamespacedName]*v1alpha1.ImageMap) (v1alpha1.KubernetesApplyStatus, error) {

        // Move the `KubernetesApply` here and it will error out
	var ka v1alpha1.KubernetesApply
	err := r.ctrlClient.Get(ctx, nn, &ka)
	if err != nil {
		return status, err
	}

	status, appliedObjects := r.forceApplyHelper(ctx, spec, imageMaps)
```
2. Run the `TestConfigMap` integration test or `tilt up` from `./integration/configmap`
3. Test should fail, saying 
```
ERROR: Build Failed: applying k8s:uncategorized: KubernetesApply.tilt.dev "uncategorized" not found
```

To see the `Get` call succeed:
1. Add a `time.Sleep(2 * time.Second)` before getting the `KubernetesApply` object
2. Or, move the call below the `forceApplyHelper`
```go
func (r *Reconciler) ForceApply(
	ctx context.Context,
	nn types.NamespacedName,
	spec v1alpha1.KubernetesApplySpec,
	imageMaps map[types.NamespacedName]*v1alpha1.ImageMap) (v1alpha1.KubernetesApplyStatus, error) {

	status, appliedObjects := r.forceApplyHelper(ctx, spec, imageMaps)

        // Move the `KubernetesApply` here and it will succeed
	var ka v1alpha1.KubernetesApply
	err := r.ctrlClient.Get(ctx, nn, &ka)
	if err != nil {
		return status, err
	}
```

**Comment by nicks** [comment]
this issue is about a deeper philosophical mismatch between how Kubernetes sees the world and how the legacy tilt control loop sees the world.

Basically: `kubectl apply` can take a long time. 

in the legacy system, tilt would synchronize the whole world to ensure that in between (a) reading the YAML to apply, and (b) writing the result of the apply, nothing is allowed to change the apply spec. You have to be a bit careful. But it can be done if you control everything.

in the k8s/controller-runtime world, their stance is that this is an impossible guarantee to make. So they've built the entire system around the assumption that objects are allowed to be out of date. They're allowed to change between (a) and (b). If they are, you should return an error. The system will try again later.

ForceApply lives between the two worlds, so takes great care to sequence things well (i.e., it does the Get() after the `kubectl apply`). But once everything is in a reconciler, the problem will go away.

**Comment by landism** [comment]
FWIW, I think of this as one of those "FYI" issues that chiefly exists so that we can link to it from a comment in the code rather than a long, distracting explanation.

> this issue is about a deeper philosophical mismatch between how Kubernetes sees the world and how the legacy tilt control loop sees the world

I think you might be talking about a different bug? Your writeup is informative but focuses heavily on spec changes and objects being out of date, but I think this case is simpler than that.

AIUI, this bug is:

The Tiltfile reconciler finishes running the Tiltfile and starts two flows that are not synchronized with each other:
  a. It dispatches a ConfigFilesReloadedAction to the Store
  b. It upserts a KubernetesApply object into the API

The flow from (a) looks something like:
a1. reducer adds manifest for k8s resource
a2. build controller decides to build manifest
a3. BaDer calls ForceApply on manifest
a4. ForceApply reads KA object from API

We have no synchronization in place to ensure (b) is complete before we hit (a4). If it has not completed, then (a4) fails because the KA object does not yet exist.

I think Lizz's tests show the slowness of `kubectl apply` is currently load-bearing, which is apparently not currently a problem in practice, but does feel racy in a way that doesn't seem very deep or philosophical (which I don't say to try be argumentative, but as evidence of why I think we're talking about different issues).

Maybe the high-level takeaway is still just "stuff is and will continue to be awkward/fragile until everything is in reconcilers", but I wanted to try to frame this particular error a bit differently since it 1) potentially has cheaper mitigations we could implement pre-reconciler if we get bitten by this again, 2) seems like it applies to other engine subscribers that might read api objects.

**Comment by nicks** [comment]
fixed by https://github.com/tilt-dev/tilt/pull/5556
