### ISSUE TITLE
AccessDenied error when trying to load dashboard!

### ISSUE THREAD

**Issue by sayjeyhi** [tilt-dev/tilt#5365]
Hi there, 
Thanks for this great job, I am living in Iran and I can't open the dashboard page most of the time. I think it is because of
using google storage API for `index.html` file. I mean for example this version file:
```
https://storage.googleapis.com/tilt-static-assets/v0.23.3/index.html
```

I am getting this error:

<img width="782" alt="Screen Shot 1400-10-20 at 01 43 58" src="https://user-images.githubusercontent.com/6254009/148703188-17fee809-2268-44b7-9537-633a586d1b1f.png">

Can't you use some other place to store dashboard files or provide an option to change this file path 😄 ?

**Comment by lianmakesthings** [comment]
Hi @sayjeyhi,
sorry to hear you're having issues accessing your dashboard.

It's very unlikely we're going to use a different CDN any time soon. But as a workaround, you could clone the codebase (since you seem to have access to Github) and run Tilt from there in dev-mode.
Here's a guide on how to do that: https://github.com/tilt-dev/tilt/blob/master/CONTRIBUTING.md

Please let us know if that helps to solve your issue.

**Comment by sayjeyhi** [comment]
Thanks, @lianmakesthings, I will check to build Tilt locally hope to be able to access the dashboard :)

**Comment by lianmakesthings** [comment]
Please let us know if you're encountering any issues @sayjeyhi.
I will leave this issue open for now. If you find this solution works for you, please close the issue.

Good luck!
