### ISSUE TITLE
Disabled resource behavior with images shared by multiple resources

### ISSUE THREAD

**Issue by nicksieger** [tilt-dev/tilt#5621]
### Expected Behavior
When two resources share an image that has live updates, only a single filewatch and imagemap is created. The disable status of those are controlled by the disable status of one of the resources, depending on ordering. This results in a situation where if you disable the resource whose configmap is connected to the filewatch, live updates will unexpectedly stop flowing to the remaining enabled resource.

### Current Behavior
Disabling one resource appears to disable live updates for a resource that shares the image with the disabled resource.

### Steps to Reproduce
- https://github.com/pandorasNox/tilt-sync-issue/

### Remediation
- Split the shared image into an image hierarchy with a base image and one image per resource so that they can be enabled/disabled separately. For an example, see the fix in pandorasNox/tilt-sync-issue#1.

**Comment by nicks** [comment]
AFAIR, we did a pretty good job abstracting out the disable decision logic, so that it should be pretty easy to only disable a filewatch if ALL the resources are disabled, cf:

https://github.com/tilt-dev/tilt/blob/master/pkg/apis/core/v1alpha1/disable_types.go#L6
https://github.com/tilt-dev/tilt/blob/master/internal/controllers/apis/configmap/disable.go#L18

@landism what do you think?

**Comment by landism** [comment]
Yeah, that sounds right.
