### ISSUE TITLE
Detect Docker build failure

### ISSUE THREAD

**Issue by Davincible** [tilt-dev/tilt#5816]
I would like my Tilt process to fail upon a failed docker build, currently it runs the entire thing regardless of the build status. 

I know there is a method `fail`, but I was unable to find a way to detect the docker build status (success / failure), is this possible? and how can I best do this?

**Comment by nicksieger** [comment]
Thanks for creating an issue! Tilt's approach is a little more holistic than a script or workflow where you can check the status after each individual operation. Maybe you can describe your setup a little more to see whether there's a way to restructure your Tiltfile to get to a faster failure?

It's helpful to think of the Tiltfile as a declarative document rather than an imperative script. So the image builds don't actually happen while the Tiltfile is executing; rather, Tilt is recording all the things you want to build and deploy and it assembles everything once the whole Tiltfile has run.

One thought I have is that if you have certain images or deployables that are key to the overall environment, you could try making a "base" k8s or docker compose resource that uses those key images, then making all or most other resources depend on that resource by using the `resource_deps` parameter. That will keep Tilt from building everything else before that key component has successfully built and deployed.

Hope this helps a bit, and feel free to describe your setup in more detail and we'll see what else we can do.

**Comment by Davincible** [comment]
Thanks for the quick reply! 
In my case it was because my ssh agent wasn't running so the Go package manager wasn't able to pull private repos in the Docker container. This specific issue was fixed by checking if the agent is running in the Tilt file, and if not start it. However I was also thinking that while developing Docker build files, it would be nice to fail the Tilt process if the Docker file has any issues.

I have a k8s deployment that uses the image, currently it just deployed the previously build image. I have briefly looked at the `resource_deps` docs for `k8s_resource` but I'm not exactly sure how to use them in my context yet

**Comment by nicksieger** [comment]
`tilt ci` will definitely fail if there are any issues building an image. The UI should also indicate failures associated with teh resources that use the image. Note that the image has to be referenced by some resource in order for it to be built -- Tilt will warn you of unused/unreferenced images and won't build them.

**Comment by Davincible** [comment]
Ahhh I `tilt ci` has the behavior I was looking for. I was using `tilt up`

**Comment by Davincible** [comment]
@nicksieger As a side note, maybe it would be nice to have a cli flag to make `tilt up` display the same failing behavior, since `tilt up` has other benefits
