### ISSUE TITLE
Release doesn't include version number bump

### ISSUE THREAD

**Issue by com6056** [tilt-dev/tilt#6206]
### Expected Behavior

Using https://raw.githubusercontent.com/tilt-dev/tilt/v0.33.4/scripts/install.sh to install Tilt should install version v0.33.4

### Current Behavior

Using https://raw.githubusercontent.com/tilt-dev/tilt/v0.33.4/scripts/install.sh to install Tilt installs version v0.33.3

It looks like the version number bumps, like https://github.com/tilt-dev/tilt/commit/f487da92f4f25bab0d8f1cd71227a3c81ef63a08, just need to be included in the current release. Not sure if there is a chicken/egg problem though.

**Comment by nicks** [comment]
Thanks for the report!

This is expected behavior; we expect people to always use the latest version of the script.

There's been some discussion about letting the install script install arbitrary versions (see: https://github.com/tilt-dev/tilt/issues/4329), but honestly, it's probably better to use `asdf` rather than rolling an artisanal tilt version manager
