### ISSUE TITLE
Container image "local/{projectname}:tilt-32d79157df88fca5" is not present with pull policy of Never

### ISSUE THREAD

**Issue by mrcam25** [tilt-dev/tilt#6228]
### Expected Behavior

After running `./up.sh` or `Tilt up` in WSL, Tilt builds locally, Kube should see this so should not look elsewhere for it.

### Current Behavior

After running `./up.sh` or `Tilt up`  in WSL, Tilt tries to build locally but gets this error:
`[event: pod {projectname}-local/{projectname}-686db65d96-5pxzc] Container image "local/{projectname}:tilt-32d79157df88fca5" is not present with pull policy of Never`

Using `docker image ls` we can see the image it's looking for is there.

### Steps to Reproduce

1. Open wsl (Ubuntu 20.04 or 22.04)
2. run ./up.sh or `tilt up`

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.31.1, built 2023-01-09
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 24.0.6
- API Version: 1.43
- Builder: 2
- Compose Version: v2.16.0
---
Kubernetes
- Env: rancher-desktop
- Context: rancher-desktop
- Cluster Name: rancher-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.27.3+k3s1
- Cluster Local Registry: none
---
...
```

**Comment by nicks** [comment]
If you can see the image in `docker image ls`, but you can't pull the image from your cluster, than this can't possibly be a tilt bug.

The problem is that you have rancher desktop configured incorrectly. you have your kubernetes context pointed at rancher desktop, but your docker socket pointed at another docker daemon that's running in WSL.
