### ISSUE TITLE
When is Tilt Coming To Production Deployments

### ISSUE THREAD

**Issue by nsgoneape** [tilt-dev/tilt#6428]
## Describe the Feature You Want
Your product is amazing. I am probably just gonna deploy the mvp for my startup on tilt on my local computer. I guess your probably not supposed to do this. I want to be able to deploy production ready services to local hardware or cloud hardware like eks.

### Current Behavior
Right now it is great just to deploy to local.

### Why Do You Want This?
I think it would make deploying microservices super easy. Honestly you could probably just create your own AWS competitor, because as a developer, even though I am new, writing as code is much simpler than navigating complex microservices ui.

**Comment by nicks** [comment]
We generally recommend using a gitops system like flux or argo to deploy stuff. Here's a post that explains why - https://blog.tilt.dev/2021/06/21/wip-vs-harness

**Comment by coopbri** [comment]
Tilt is awesome because it allows you to stitch all kinds of services together (vanilla Docker/Podman, Compose, Swarm, Kubernetes resources, shell scripts). ArgoCD and Flux require a K8s cluster and setup, whereas Tilt does not need this base layer of infrastructure. I understand this use case is not recommended by the Tilt team, but is there a way to do this? Is it a risk?

**Comment by coopbri** [comment]
Here is an updated, working link for @nicks above: https://blog.tilt.dev/2021/06/21/wip-vs-harness.html

**Comment by nicks** [comment]
Thanks @coopbri ! We switched the static site host earlier this week and misconfigured it a bit, both links should work now!
